export const goods = ["Apparel","Electronics", "Groceries","Cosmetics", "Home appliances","Books", "Financial services", "Healthcare services", "Transportation services", "Hospitality services", "Education services", "Fitness services" ]

export const languages = [
  { name: "Arabic", value: "ar" },
  { name: "Chinese", value: "zh" },
  { name: "Dutch", value: "nl" },
  { name: "English", value: "en" },
  { name: "French", value: "fr" },
  { name: "German", value: "de" },
  { name: "Greek", value: "el" },
  { name: "Hebrew", value: "he" },
  { name: "Hindi", value: "hi" },
  { name: "Italian", value: "it" },
  { name: "Japanese", value: "ja" },
  { name: "Malayalam", value: "ml" },
  { name: "Marathi", value: "mr" },
  { name: "Norwegian", value: "no" },
  { name: "Portuguese", value: "pt" },
  { name: "Romanian", value: "ro" },
  { name: "Russian", value: "ru" },
  { name: "Spanish", value: "es" },
  { name: "Swedish", value: "sv" },
  { name: "Tamil", value: "ta" },
  { name: "Telugu", value: "te" },
  { name: "Ukrainian", value: "uk" },
];

export const countries = [
  { name: "Australia", value: "au" },
  { name: "Brazil", value: "br" },
  { name: "Canada", value: "ca" },
  { name: "China", value: "cn" },
  { name: "Egypt", value: "eg" },
  { name: "France", value: "fr" },
  { name: "Germany", value: "de" },
  { name: "Greece", value: "gr" },
  { name: "Hong Kong", value: "hk" },
  { name: "India", value: "in" },
  { name: "Ireland", value: "ie" },
  { name: "Israel", value: "il" },
  { name: "Italy", value: "it" },
  { name: "Japan", value: "jp" },
  { name: "Netherlands", value: "nl" },
  { name: "Norway", value: "no" },
  { name: "Pakistan", value: "pk" },
  { name: "Peru", value: "pe" },
  { name: "Philippines", value: "ph" },
  { name: "Portugal", value: "pt" },
  { name: "Romania", value: "ro" },
  { name: "Russian Federation", value: "ru" },
  { name: "Singapore", value: "sg" },
  { name: "Spain", value: "es" },
  { name: "Sweden", value: "se" },
  { name: "Switzerland", value: "ch" },
  { name: "Taiwan", value: "tw" },
  { name: "Ukraine", value: "ua" },
  { name: "United Kingdom", value: "gb" },
  { name: "United States", value: "us" },
];
